### ISSUE TITLE
Merging xml fails

### ISSUE THREAD

**Issue by schmiedc** [fiji/SPIM_Registration#105]
Hi Stephan,

I have a issue with failing of the merging of the xml files for my cluster workflow.
Here is the log file of the failed processing. Please find attached also the .xml files in question.

Thanks a lot!
Christopher

[xml.zip](https://github.com/fiji/SPIM_Registration/files/356847/xml.zip)

12 cores available for multi-threading
Threads: 1
Load Parameters:
directory=/lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/
merged_xml=dataset_merge.xml
=======================================================
Start to merge .xml files
Attempting to merge the following XML's in directory '/lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/':
  /lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/.job_2.xml
  /lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/dataset.job_01.xml
  /lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/.job_0.xml
  /lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/dataset.job_00.xml
  /lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/dataset.job_02.xml
  /lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/.job_1.xml
Failed to merge XML's: mpicbg.spim.data.SpimDataException: Could not find corresponding ViewSetupId=1 in xml '/lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/dataset.job_01.xml'
mpicbg.spim.data.SpimDataException: Could not find corresponding ViewSetupId=1 in xml '/lustre/projects/project-akanksha/Akanksha/16-06-22_LZ2_VW_sqhGFPinj_embryoI_25C_5angles_5min_CHORION!/dataset.job_01.xml'
	at spim.fiji.plugin.cluster.MergeClusterJobs.merge(MergeClusterJobs.java:66)
	at spim.fiji.plugin.Merge_Cluster_Jobs.run(Merge_Cluster_Jobs.java:93)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at ij.IJ.run(IJ.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at bsh.Reflect.invokeMethod(Unknown Source)
	at bsh.Reflect.invokeStaticMethod(Unknown Source)
	at bsh.Name.invokeMethod(Unknown Source)
	at bsh.BSHMethodInvocation.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
	at bsh.BSHBlock.evalBlock(Unknown Source)
	at bsh.BSHBlock.eval(Unknown Source)
	at bsh.BSHBlock.eval(Unknown Source)
	at bsh.BSHTryStatement.eval(Unknown Source)
	at bsh.Interpreter.eval(Unknown Source)
	at bsh.Interpreter.source(Unknown Source)
	at bsh.Interpreter.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:184)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76)

**Comment by schmiedc** [comment]
Retested. Does not occur anymore. Sorry!
