### ISSUE TITLE
Fusing images issues

### ISSUE THREAD

**Issue by lacan** [fiji/SPIM_Registration#125]
Exception when using "Quick Display"
========================

When trying out Quick Display of the new MultiView Reconstruction Application I get the following error
`Exception in thread "Thread-20" java.lang.NoClassDefFoundError: net/imglib2/cache/img/ReadOnlyCachedCellImgOptions
	at spim.process.fusion.FusionHelper.cacheRandomAccessibleInterval(FusionHelper.java:104)
	at spim.fiji.spimdata.explorer.popup.DisplayFusedImagesPopup$DisplayVirtualFused$1.run(DisplayFusedImagesPopup.java:238)
	at java.lang.Thread.run(Thread.java:745)
`

Exception with Cached Fusion, which seems linked to the same issue as above
===================

`Exception in thread "Thread-22" java.lang.NoClassDefFoundError: net/imglib2/cache/img/ReadOnlyCachedCellImgOptions
	at spim.process.fusion.FusionHelper.cacheRandomAccessibleInterval(FusionHelper.java:104)
	at spim.fiji.spimdata.explorer.popup.DisplayFusedImagesPopup$DisplayVirtualFused$1.run(DisplayFusedImagesPopup.java:238)
	at java.lang.Thread.run(Thread.java:745)
`
Fused, Virtual
=========
Images are called `Fused, Virtual` even if we use the 'precompute' option

**Comment by tpietzsch** [comment]
@lacan Fiji had an outdated version `imglib2-cache-1.0.0-beta-5.jar`. I just uploaded the most recent one. Could you try whether this solves the issue?

**Comment by lacan** [comment]
@tpietzsch Hi!
Unfortunately it has made the options no longer show up on the menu. sometimes it says `Cached`, others `Virtual` or `Precomputed`
![image](https://user-images.githubusercontent.com/319932/27828429-799c606a-60bc-11e7-9777-4b661d9f5349.png)

Similarily clicking on "Fuse Images..." now does nothing. There is no Console output or error message to help make sense of the situation. 

Best
Oli

**Comment by tpietzsch** [comment]
hmm, what a mess... I guess we will have to wait for @StephanPreibisch to comment on that.

**Comment by hoerldavid** [comment]
Hi @lacan,
the menu items should start working once you define at least one Bounding Box. The `NoClassDefFoundError` should also be gone thanks to the update by @tpietzsch.

Just to make sure we are on the same page:
You are using the new `SPIM_Registration` from the `BigStitcher` update site?

All the best,
David

**Comment by hoerldavid** [comment]
Regarding the grayed out menu item:
This indicates how the `Quick Display` will be done (cached by default). 
Clicking it will cycle through the options (`Cached` -> `Precomputed` -> `Virtual` -> ... )

**Comment by StephanPreibisch** [comment]
Hi, yes, we should show another message if no bounding boxes are defined @hoerldavid ... we'll do that tomorrow in Munich. But the missing imglib2-cache was definitely the problem, thanks for fixing that @tpietzsch. @lacan - you need to define bounding boxes for the quick display to work.

**Comment by hoerldavid** [comment]
Finally, regarding the `Fused, Virtual` image title:
This was indeed hardcoded. I just enabled it to change according to the fusion method used.
This will be part of the next release.

**Comment by StephanPreibisch** [comment]
thanks @hoerldavid

**Comment by tpietzsch** [comment]
👍

**Comment by tpietzsch** [comment]
> Regarding the grayed out menu item:
> This indicates how the Quick Display will be done (cached by default).
> Clicking it will cycle through the options (Cached -> Precomputed -> Virtual -> ... )

Seems a bit unintuitive. Why not actually offer 3 options with the active one checked?
(Like this)
```
| Quick Display | --> | X Cached      |
                      |   Precomputed |
                      |   Virtual     |
```

...but maybe I also misunderstand what this actually is expected to do...

**Comment by StephanPreibisch** [comment]
That sounds reasonable, let's do that ... it is in alpha status after all :)
