### ISSUE TITLE
How to transform data to use the minimum bounding box

### ISSUE THREAD

**Issue by lacan** [fiji/SPIM_Registration#128]
In the previous iteration of the MultiView tool, one could bake a manual BDV transform before defining a bounding box in order to minimize the volume that needed to be fused. 

Currently the "Apply BDV Transformation to Data" does not affect the position of the bounding box. 

I also tried grouping the views together and making a manual transform of all the views together, also no effect. 

I noticed that I could transform the bounding box directly as it is an object of the BDV and so is sensitive to the 't' transform command.

For all these, however the result is still based on the original orientation of the dataset (or bounding box). 

Is it currently not possible to reorient the dataset in order to minimize the bounding box or am I doing something wrong?

Best
Oli

**Comment by lacan** [comment]
Hi. 

Any news on this front? Should I provide more information?

Best

Oli

**Comment by StephanPreibisch** [comment]
Hi, I tested it and it works for me. Can you maybe be more specific?

**Comment by lacan** [comment]
Hi
Tested what and in what order should I do the steps?

Before I could move the dataset around, then just click Apply BDV Transform to Data before creating a bounding box. 

right now when I click Applz BDV Transform, it has no effect on the bounding box.

If I start making a bounding box interactively, I can hit 't' and move it around, which is not so intuitive, then press 't' again but this has no effect on the resulting exported image.

**Comment by lacan** [comment]
OK I think I found what I was doing wrong but now I get an other error

After stitching the tiles, I move to the Multiview part of the Application and use 'Interactively Reorient Sample...'
After I move the dataset to the orientation I want, I use 'Apply Transformation', so far so good. 

Now when I go to create a bounding boz, I am greeted with the following error

```
Exception in thread "Thread-24" java.lang.IllegalArgumentException: invalid range properties
	at javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:102)
	at javax.swing.JSlider.<init>(JSlider.java:274)
	at bdv.tools.brightness.SliderPanel.<init>(SliderPanel.java:73)
	at bdv.tools.boundingbox.BoxSelectionPanel.<init>(BoxSelectionPanel.java:88)
	at bdv.tools.boundingbox.BoundingBoxDialog.<init>(BoundingBoxDialog.java:150)
	at bdv.tools.boundingbox.BoundingBoxDialog.<init>(BoundingBoxDialog.java:90)
	at spim.process.boundingbox.BoundingBoxBigDataViewer$1.<init>(BoundingBoxBigDataViewer.java:101)
	at spim.process.boundingbox.BoundingBoxBigDataViewer.estimate(BoundingBoxBigDataViewer.java:100)
	at spim.fiji.plugin.boundingbox.BDVBoundingBoxGUI.setUpDefaultValues(BDVBoundingBoxGUI.java:29)
	at spim.fiji.plugin.boundingbox.BoundingBoxGUI.getSimpleDialog(BoundingBoxGUI.java:131)
	at spim.fiji.plugin.boundingbox.BoundingBoxGUI.queryParameters(BoundingBoxGUI.java:71)
	at spim.fiji.plugin.Define_Bounding_Box.defineBoundingBox(Define_Bounding_Box.java:109)
	at spim.fiji.plugin.Define_Bounding_Box.defineBoundingBox(Define_Bounding_Box.java:60)
	at spim.fiji.spimdata.explorer.popup.BoundingBoxPopup$MyActionListener$1.run(BoundingBoxPopup.java:66)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by StephanPreibisch** [comment]
Ok, I'll try again and post exactly what I did, but this worked for me. I wonder what the difference is. I'll try to do this tomorrow or latest on Monday!

**Comment by lacan** [comment]
Dear @StephanPreibisch , Any update on this?

Best

Oli
