### ISSUE TITLE
Error when resaving multichannel CZI to HDF5

### ISSUE THREAD

**Issue by lacan** [fiji/SPIM_Registration#91]
Seems that the channel indexes are 0-based and that the resave plugin is 1-based

`java.lang.RuntimeException: File 'BOB.czi' has only channels [0 ... 1], but you want to open channel 2. Stopping.
	at spim.fiji.spimdata.imgloaders.LegacyStackImgLoaderLOCI.openLOCI(LegacyStackImgLoaderLOCI.java:290)
	at spim.fiji.spimdata.imgloaders.LegacyStackImgLoaderLOCI.getImage(LegacyStackImgLoaderLOCI.java:125)
	at mpicbg.spim.data.legacy.LegacyImgLoaderWrapper$SetupImgLoaderWrapper.getImage(LegacyImgLoaderWrapper.java:79)
	at bdv.export.WriteSequenceToHdf5.writeHdf5PartitionFile(WriteSequenceToHdf5.java:441)
	at bdv.export.WriteSequenceToHdf5.writeHdf5File(WriteSequenceToHdf5.java:154)
	at spim.fiji.plugin.resave.Generic_Resave_HDF5.writeHDF5(Generic_Resave_HDF5.java:220)
	at spim.fiji.plugin.resave.Resave_HDF5.run(Resave_HDF5.java:88)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.Executer.runCommand(Executer.java:136)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:662)
`

**Comment by tpietzsch** [comment]
@lacan Can you provide example data that shows the problem?

**Comment by lacan** [comment]
@tpietzsch I could. The whole multiangle dataset is 65Gb, but a single angle is 10GB. Is there some service you would know that can accept this size?

**Comment by spimager** [comment]
Google Drive comes with 15GB storage by default.
